# Generated by Django 3.2.6 on 2021-08-30 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TIENDA_APP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mi_modelo',
            name='codigo_seguridad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mi_modelo',
            name='number_tarjeta',
            field=models.IntegerField(),
        ),
    ]
