# Generated by Django 3.2.6 on 2021-11-19 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TIENDA_APP', '0002_auto_20210830_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='mi_modelo',
            name='contraseña',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mi_modelo',
            name='usuario',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
