# Generated by Django 3.2.6 on 2021-11-19 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TIENDA_APP', '0003_auto_20211119_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mi_modelo',
            name='codigo_seguridad',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mi_modelo',
            name='fecha_tarjeta',
            field=models.DateField(null=True),
        ),
    ]
